/**
 * SEO Keywords & Metadata
 * 100+ Keywords in English and Spanish
 * Worldwide targeting for entrepreneurship and business
 */

export const SEO_KEYWORDS = {
  // English Keywords - Business Tools & Planning (25 keywords)
  business_tools_en: [
    'business plan generator',
    'business planning software',
    'startup business plan',
    'financial projections tool',
    'business model canvas',
    'SWOT analysis template',
    'market sizing calculator',
    'TAM calculator startup',
    'business analysis tool',
    'entrepreneurship software',
    'startup tools',
    'business intelligence platform',
    'competitive analysis tool',
    'market research tool',
    'investor readiness checker',
    'startup viability calculator',
    'business valuation tool',
    'EBITDA calculator',
    'startup naming tool',
    'business model generator',
    'financial modeling software',
    'startup metrics dashboard',
    'unit economics calculator',
    'CAC payback period calculator',
    'LTV calculator business',
  ],

  // English Keywords - Fundraising & Investor Relations (20 keywords)
  fundraising_en: [
    'investor readiness assessment',
    'startup pitch deck generator',
    'investor targeting tool',
    'Series A funding guide',
    'VC due diligence checklist',
    'equity dilution calculator',
    'valuation estimate tool',
    'cap table management',
    'pitch to investors guide',
    'venture capital metrics',
    'angel investment criteria',
    'startup funding strategy',
    'pre-seed funding guide',
    'fundraising timeline',
    'investor relations software',
    'investor pitch platform',
    'funding round strategy',
    'venture funding database',
    'investor benchmarking',
    'startup valuation methods',
  ],

  // English Keywords - Analysis & Strategy (20 keywords)
  analysis_en: [
    'competitive analysis framework',
    'industry analysis template',
    'market opportunity analysis',
    'Porter five forces analysis',
    'strategic planning tool',
    'business strategy framework',
    'growth strategy generator',
    'market entry strategy',
    'customer acquisition strategy',
    'retention strategy planning',
    'pricing strategy tool',
    'go-to-market strategy',
    'business intelligence tool',
    'data analytics platform',
    'performance metrics dashboard',
    'KPI tracking software',
    'benchmarking tool',
    'scenario planning software',
    'financial forecasting tool',
    'risk analysis framework',
  ],

  // English Keywords - SaaS & Metrics (20 keywords)
  saas_en: [
    'SaaS metrics dashboard',
    'recurring revenue calculator',
    'MRR calculator',
    'ARR calculator',
    'churn rate analysis',
    'customer lifetime value calculator',
    'customer acquisition cost tool',
    'SaaS benchmarking',
    'SaaS financial model',
    'SaaS unit economics',
    'expansion revenue calculator',
    'net revenue retention calculator',
    'SaaS valuation model',
    'burn rate calculator',
    'runway calculator',
    'cohort analysis tool',
    'retention curve analysis',
    'NPS tracking software',
    'SaaS metrics template',
    'SaaS growth model',
  ],

  // English Keywords - General Entrepreneurship (15 keywords)
  entrepreneurship_en: [
    'startup checklist',
    'entrepreneur resources',
    'startup guide',
    'business startup help',
    'small business planning',
    'entrepreneurship platform',
    'business plan examples',
    'startup success factors',
    'business growth strategies',
    'startup challenges',
    'entrepreneur toolkit',
    'startup education',
    'business mentorship platform',
    'startup community',
    'entrepreneur networking',
  ],

  // Spanish Keywords - Business Tools & Planning (25 keywords)
  business_tools_es: [
    'generador de plan de negocios',
    'software de planificación empresarial',
    'plan de negocio para startups',
    'proyecciones financieras herramienta',
    'canvas modelo de negocio',
    'análisis FODA plantilla',
    'calculadora de tamaño de mercado',
    'calculadora TAM startup',
    'herramienta de análisis empresarial',
    'software de emprendimiento',
    'herramientas para startups',
    'plataforma de inteligencia empresarial',
    'herramienta de análisis competitivo',
    'herramienta de investigación de mercado',
    'verificador de disposición de inversor',
    'calculadora de viabilidad de negocio',
    'herramienta de valuación empresarial',
    'calculadora EBITDA',
    'generador de nombres de startups',
    'generador de modelos de negocio',
    'software de modelado financiero',
    'dashboard de métricas de startup',
    'calculadora de economía unitaria',
    'calculadora de CAC payback',
    'calculadora LTV negocio',
  ],

  // Spanish Keywords - Fundraising & Investor Relations (20 keywords)
  fundraising_es: [
    'evaluación de disposición de inversor',
    'generador de pitch deck',
    'herramienta de direccionamiento de inversores',
    'guía de financiación Serie A',
    'lista de verificación de diligencia debida VC',
    'calculadora de dilución de capital',
    'herramienta de estimación de valuación',
    'gestión de cap table',
    'guía para presentar a inversores',
    'métricas de capital de riesgo',
    'criterios de inversión ángel',
    'estrategia de financiación de startups',
    'guía de financiación pre-seed',
    'cronograma de recaudación de fondos',
    'software de relaciones con inversores',
    'plataforma de pitch para inversores',
    'estrategia de ronda de financiación',
    'base de datos de financiación de ventures',
    'benchmarking de inversores',
    'métodos de valuación de startups',
  ],

  // Spanish Keywords - Analysis & Strategy (20 keywords)
  analysis_es: [
    'marco de análisis competitivo',
    'plantilla de análisis de industria',
    'análisis de oportunidad de mercado',
    'análisis de cinco fuerzas de Porter',
    'herramienta de planificación estratégica',
    'marco de estrategia empresarial',
    'generador de estrategia de crecimiento',
    'estrategia de entrada al mercado',
    'estrategia de adquisición de clientes',
    'planificación de estrategia de retención',
    'herramienta de estrategia de precios',
    'estrategia de comercialización',
    'herramienta de inteligencia empresarial',
    'plataforma de análisis de datos',
    'dashboard de métricas de desempeño',
    'software de seguimiento de KPI',
    'herramienta de benchmarking',
    'software de planificación de escenarios',
    'herramienta de pronóstico financiero',
    'marco de análisis de riesgos',
  ],

  // Spanish Keywords - SaaS & Metrics (20 keywords)
  saas_es: [
    'dashboard de métricas SaaS',
    'calculadora de ingresos recurrentes',
    'calculadora MRR',
    'calculadora ARR',
    'análisis de tasa de rotación',
    'calculadora de valor de vida del cliente',
    'herramienta de costo de adquisición',
    'benchmarking de SaaS',
    'modelo financiero SaaS',
    'economía unitaria SaaS',
    'calculadora de ingresos por expansión',
    'calculadora de retención neta de ingresos',
    'modelo de valuación SaaS',
    'calculadora de velocidad de quema',
    'calculadora de pista',
    'herramienta de análisis de cohortes',
    'análisis de curva de retención',
    'software de seguimiento NPS',
    'plantilla de métricas SaaS',
    'modelo de crecimiento SaaS',
  ],

  // Spanish Keywords - General Entrepreneurship (15 keywords)
  entrepreneurship_es: [
    'lista de verificación de startups',
    'recursos para emprendedores',
    'guía de startups',
    'ayuda para iniciar negocio',
    'planificación de pequeño negocio',
    'plataforma de emprendimiento',
    'ejemplos de plan de negocios',
    'factores de éxito de startup',
    'estrategias de crecimiento empresarial',
    'desafíos de startups',
    'kit de herramientas del emprendedor',
    'educación sobre startups',
    'plataforma de mentoría empresarial',
    'comunidad de startups',
    'red de emprendedores',
  ],
};

export const LONG_TAIL_KEYWORDS = {
  english: [
    'how to write a business plan for a startup',
    'best business planning software for startups',
    'startup financial projection template',
    'how to calculate market size for startup',
    'SWOT analysis template for business',
    'investor readiness checklist for startups',
    'how to pitch to investors as a startup founder',
    'business valuation methods for startups',
    'unit economics for SaaS businesses',
    'how to reduce customer acquisition costs',
    'calculating lifetime value of customers',
    'Series A fundraising timeline and process',
    'competitive analysis framework for startups',
    'go-to-market strategy for new products',
    'how to calculate startup burn rate',
    'venture capital due diligence process',
    'startup KPI dashboard and metrics',
    'business model canvas explained',
    'Porter five forces analysis example',
    'pricing strategy for SaaS startups',
  ],
  spanish: [
    'cómo escribir un plan de negocios para startup',
    'mejor software de planificación empresarial',
    'plantilla de proyección financiera startup',
    'cómo calcular el tamaño del mercado',
    'plantilla de análisis FODA para negocios',
    'lista de verificación de disposición de inversor',
    'cómo presentar a inversores como fundador',
    'métodos de valuación empresarial para startups',
    'economía unitaria para negocios SaaS',
    'cómo reducir costo de adquisición de clientes',
    'calculando valor de vida del cliente',
    'proceso de financiación Serie A',
    'marco de análisis competitivo para startups',
    'estrategia de comercialización de productos',
    'cómo calcular la velocidad de quema startup',
    'proceso de diligencia debida de capital de riesgo',
    'dashboard de KPI y métricas startup',
    'canvas modelo de negocio explicado',
    'ejemplo de análisis cinco fuerzas Porter',
    'estrategia de precios para SaaS',
  ],
};

export const SEO_CONFIG = {
  siteName: 'MIZHAR',
  siteDescription: 'AI-powered business intelligence platform for entrepreneurs. Create business plans, analyze markets, and get intelligent insights to scale your startup.',
  siteDescriptionES: 'Plataforma de inteligencia empresarial impulsada por IA para emprendedores. Crea planes de negocio, analiza mercados y obtén información inteligente para escalar tu startup.',

  pageMetadata: {
    home: {
      title: 'MIZHAR - AI Business Intelligence Platform for Startups',
      description: 'Build winning business plans, analyze competitors, and get AI-powered insights. Free tools for entrepreneurs. Pro features for serious founders.',
      titleES: 'MIZHAR - Plataforma de Inteligencia Empresarial IA para Startups',
      descriptionES: 'Construye planes de negocio ganadores, analiza competidores y obtén información impulsada por IA. Herramientas gratuitas para emprendedores.',
    },
  },
};
