#!/bin/bash
echo "🔍 AUDITANDO CÓDIGO..."
echo ""
echo "1. Verificando Prisma..."
grep -r "prisma" package.json && echo "❌ PRISMA FOUND" || echo "✅ No Prisma"
echo ""
echo "2. Verificando next.config..."
ls next.config.ts 2>/dev/null && echo "❌ TIENE next.config.ts" || echo "✅ No tiene .ts"
ls next.config.js 2>/dev/null && echo "✅ TIENE next.config.js" || echo "❌ FALTA .js"
echo ""
echo "3. Verificando estructura..."
ls -la src/app/layout.tsx 2>/dev/null && echo "✅ layout.tsx existe" || echo "❌ FALTA layout"
ls -la src/lib/seo.tsx 2>/dev/null && echo "✅ seo.tsx existe" || echo "❌ FALTA seo"
echo ""
echo "✅ AUDITORÍA COMPLETA"
