/**
 * POST /api/blog/generate
 *
 * Trigger blog post generation from analyzed cases and save to database.
 * This endpoint can be called after cases have been analyzed.
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
);

// Mock blog post generator (in production, would call Python module or Claude API)
function generateBlogPost(caseData: any): any {
  const caseName = caseData.name;
  const slug = caseName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  // Extract key insights from case analysis
  const verdict = caseData.verdict || 'UNKNOWN';
  const riskScore = caseData.risk_score || 5;
  const analysis = caseData.challenge_analysis || {};
  const issues = caseData.critical_issues || [];
  const alternatives = caseData.strategic_alternatives || '';

  // Generate excerpt
  let excerpt = `Deep Challenge Mode analysis of ${caseName}. `;
  if (verdict === 'PASS') {
    excerpt += `Strong investment candidate with low risk profile (${riskScore}/10).`;
  } else if (verdict === 'CONDITIONAL') {
    excerpt += `Conditional opportunity with moderate risk (${riskScore}/10). Requires strategic adjustments.`;
  } else {
    excerpt += `Significant challenges identified (${riskScore}/10). Major issues require addressing.`;
  }

  // Generate content
  const content = `# ${caseName}: In-Depth Challenge Mode Analysis

## Executive Summary

This is a detailed Challenge Mode analysis of **${caseName}**, using aggressive VC-style critique to evaluate the company's investment potential.

### Key Metrics
- **Verdict**: ${verdict}
- **Risk Score**: ${riskScore}/10
- **Stage**: ${caseData.stage || 'Unknown'}
- **Sectors**: ${caseData.sectors?.join(', ') || 'Unknown'}
- **Funding**: $${((caseData.total_funding || 0) / 1_000_000_000).toFixed(1)}B

---

## Challenge Mode Analysis

Our framework evaluates ${caseName} across critical dimensions:

### Unit Economics
The company's CAC, LTV, and payback period are evaluated against venture benchmarks. We analyze burn multiple and capital efficiency to understand sustainability.

### Competitive Moat
We assess defensibility through switching costs, network effects, and brand strength. Can competitors easily replicate this model?

### Market Opportunity
TAM/SAM/SOM validation ensures the addressable market is sufficient for venture scale returns. Market growth rates and dynamics are evaluated.

### Founder Quality & Team
Track record, domain expertise, and team composition are critical. We evaluate founder fit and ability to hire and retain top talent.

### Growth & Scalability
Repeatability, unit economics at scale, and capital efficiency determine if the model can sustain high growth.

---

## Critical Issues

${issues.length > 0 ? issues.map((issue: string) => `- **${issue}**`).join('\n') : 'No critical issues identified'}

---

## Strategic Alternatives

Rather than the current path, consider:

${alternatives || 'Alternative strategies should be evaluated based on market conditions and competitive dynamics.'}

---

## Final Verdict: ${verdict}

${
  verdict === 'PASS'
    ? `${caseName} demonstrates strong fundamentals with manageable risk. This company shows clear venture potential with strong unit economics, sustainable competitive advantages, and experienced leadership. Recommended for further due diligence.`
    : verdict === 'CONDITIONAL'
    ? `${caseName} shows promise but requires strategic adjustments. Key metrics are positive, but execution risks and market dynamics require monitoring. Success depends on addressing critical issues and executing against ambitious growth targets.`
    : `${caseName} faces significant challenges that must be resolved. While the team and market opportunity may be strong, current execution or unit economics present material concerns. Major strategic pivots may be required.`
}

---

## Methodology

This analysis uses Challenge Mode, an aggressive VC-style framework that evaluates startups through a critical lens. We examine:

- Unit economics and capital efficiency
- Competitive defensibility and moats
- Market sizing and TAM validation
- Team quality and domain expertise
- Growth model repeatability and scalability
- Execution risk and milestone achievement

---

## Disclaimer

This analysis is AI-generated based on public information and standard VC frameworks. It is not professional investment advice, a formal recommendation, or verified through direct company interaction. Use as research input only.

Generated by MIZHAR Challenge Mode Analysis Engine`;

  return {
    title: `${caseName}: In-Depth Challenge Mode Analysis`,
    slug,
    excerpt,
    content,
    tags: [
      'venture-analysis',
      caseData.stage?.toLowerCase() || 'startup',
      (caseData.sectors?.[0] || 'technology').toLowerCase(),
      verdict.toLowerCase(),
    ],
    sectors: caseData.sectors || ['Technology'],
    read_time: Math.max(5, Math.ceil(content.split(' ').length / 200)),
  };
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { case_ids, publish = false } = body;

    if (!case_ids || !Array.isArray(case_ids) || case_ids.length === 0) {
      return NextResponse.json(
        { error: 'case_ids array is required' },
        { status: 400 }
      );
    }

    // Fetch analyzed cases from database
    const { data: cases, error: fetchError } = await supabase
      .from('startup_cases')
      .select(
        `
        id,
        name,
        description,
        stage,
        sectors,
        total_funding,
        data_source,
        case_analyses (
          id,
          verdict,
          risk_score,
          challenge_analysis,
          critical_issues,
          strategic_alternatives
        )
      `
      )
      .in('id', case_ids);

    if (fetchError) {
      console.error('Error fetching cases:', fetchError);
      return NextResponse.json(
        { error: 'Failed to fetch cases' },
        { status: 500 }
      );
    }

    if (!cases || cases.length === 0) {
      return NextResponse.json(
        { error: 'No cases found' },
        { status: 404 }
      );
    }

    // Generate blog posts for each case
    const generatedPosts = [];
    const savedPosts = [];
    const errors = [];

    for (const caseData of cases) {
      try {
        // Get latest analysis
        const analysis = caseData.case_analyses?.[0];

        if (!analysis) {
          errors.push(`Case ${caseData.name}: No analysis found`);
          continue;
        }

        // Generate blog post
        const blogPost = generateBlogPost({
          ...caseData,
          ...analysis,
          challenge_analysis: analysis.challenge_analysis?.analysis || '',
        });

        generatedPosts.push(blogPost);

        // Save to database
        const { data: insertedPost, error: insertError } = await supabase
          .from('blog_posts')
          .insert({
            title: blogPost.title,
            slug: blogPost.slug,
            excerpt: blogPost.excerpt,
            content: blogPost.content,
            case_id: caseData.id,
            case_name: caseData.name,
            tags: blogPost.tags,
            sectors: blogPost.sectors,
            published: publish,
            author: 'MIZHAR Analysis',
            read_time: blogPost.read_time,
            published_at: new Date().toISOString(),
          })
          .select();

        if (insertError) {
          errors.push(`Case ${caseData.name}: ${insertError.message}`);
        } else {
          savedPosts.push(insertedPost?.[0]);
        }
      } catch (err) {
        errors.push(`Case ${caseData.name}: ${err instanceof Error ? err.message : 'Unknown error'}`);
      }
    }

    return NextResponse.json({
      success: true,
      generated: generatedPosts.length,
      saved: savedPosts.length,
      published: publish,
      posts: savedPosts,
      errors: errors.length > 0 ? errors : undefined,
    });
  } catch (error) {
    console.error('Blog generation API error:', error);
    return NextResponse.json(
      {
        error: 'Failed to generate blog posts',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
