"""
MIZHAR Blog Generator Module

Phase 3 of SPRINT 2: Real Case Studies System
Converts analyzed startup cases into publishable blog content.

Features:
- Case study post generation with SEO optimization
- Comparison posts between similar startups
- Markdown and HTML output formats
- Front matter (metadata) generation
- Database integration for blog_posts table
"""

import json
import logging
import re
from typing import Dict, List, Optional
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)


def slugify(text: str) -> str:
    """Simple slug generation without external dependencies."""
    # Convert to lowercase and remove special characters
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    text = text.strip('-')
    return text


class BlogGenerator:
    """Generates blog content from analyzed startup cases."""

    def __init__(self):
        self.posts = []
        self.generated_at = datetime.now().isoformat()

    def _sanitize_for_markdown(self, text: str) -> str:
        """Clean text for markdown output."""
        # Replace special characters
        text = text.replace('"', '"').replace('"', '"')
        text = text.replace("'", "'").replace("'", "'")
        return text.strip()

    def generate_case_post(self, analysis: Dict) -> Dict:
        """
        Generate a blog post from a single case analysis.

        Args:
            analysis: Complete case analysis result

        Returns:
            Blog post with front matter and content
        """
        startup_name = analysis.get("startup_name", "Unknown Startup")
        original_data = analysis.get("original_data", {})
        challenge_analysis = analysis.get("challenge_analysis", {})
        alternatives = analysis.get("strategic_alternatives", {})

        # Extract key metrics
        analysis_text = challenge_analysis.get("analysis", "")

        # Generate slug
        slug = slugify(startup_name)

        # Create front matter
        front_matter = {
            "title": f"{startup_name}: Deep VC Critique & Analysis",
            "slug": slug,
            "date": datetime.now().isoformat(),
            "author": "MIZHAR AI",
            "summary": f"In-depth Challenge Mode analysis of {startup_name}. Risk assessment, critical issues, and strategic alternatives.",
            "tags": [
                "venture-analysis",
                original_data.get("stage", "").lower(),
                original_data.get("sectors", ["technology"])[0].lower(),
            ],
            "source": original_data.get("data_source", "unknown"),
            "canonical": f"https://mizhar.io/blog/{slug}",
        }

        # Generate markdown content
        content = f"""# {startup_name}: Deep VC Critique & Analysis

## Executive Summary

This is a detailed Challenge Mode analysis of **{startup_name}**.

### Quick Stats
- **Stage**: {original_data.get('stage', 'Unknown')}
- **Market**: {original_data.get('market', original_data.get('sectors', ['Unknown'])[0])}
- **Funding Ask**: ${original_data.get('total_funding', 0):,}
- **Source**: {original_data.get('data_source', 'Unknown')}

---

## The Challenge

Our AI venture analysis engine applied aggressive VC-style critique using Challenge Mode analysis:

{self._extract_analysis_section(analysis_text, 'CHALLENGE')}

---

## Critical Assessment

### Risk Score
{self._extract_risk_score(analysis_text)}

### Critical Issues
{self._extract_critical_issues(analysis_text)}

### Major Concerns
{self._extract_major_concerns(analysis_text)}

---

## Strategic Alternatives

Rather than accept the current business model, here's what could work better:

{self._format_alternatives(alternatives)}

---

## What This Means

This analysis is based on evidence-driven venture capital frameworks including:
- **Unit Economics**: CAC, LTV, payback period, burn multiple
- **Competitive Moat**: Defensibility, switching costs, network effects
- **Market Sizing**: TAM/SAM/SOM validation
- **Founder Quality**: Track record, domain expertise
- **Growth Model**: Repeatability, scalability, capital efficiency

---

## Disclaimer

This analysis is generated by AI based on public information and standard VC frameworks. It is not:
- Professional investment advice
- A formal investment recommendation
- Verified by direct company interaction
- Accounting or legal analysis

Use as research input only.

---

*Analysis generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} by MIZHAR AI*
"""

        post = {
            "slug": slug,
            "front_matter": front_matter,
            "content": content,
            "markdown": f"---\n{json.dumps(front_matter, indent=2)}\n---\n\n{content}",
            "generated_at": datetime.now().isoformat(),
        }

        self.posts.append(post)
        return post

    def _extract_analysis_section(self, text: str, section: str) -> str:
        """Extract a specific section from analysis text."""
        lines = text.split("\n")
        section_lines = []
        capture = False

        for line in lines:
            if section in line and "VERDICT" not in line:
                capture = True
                continue
            elif capture and ("---" in line or line.strip().startswith("##")):
                break
            elif capture and line.strip():
                section_lines.append(line)

        return "\n".join(section_lines) if section_lines else "See full analysis below."

    def _extract_risk_score(self, text: str) -> str:
        """Extract risk score from analysis."""
        import re
        match = re.search(r"Risk Score:\s*(\d+)/10", text)
        if match:
            score = int(match.group(1))
            bar_length = 10
            filled = int((score / 10) * bar_length)
            bar = "█" * filled + "░" * (bar_length - filled)
            return f"**Risk Score: {score}/10**\n\n```\n{bar} {score}/10\n```"
        return "Risk score not available"

    def _extract_critical_issues(self, text: str) -> str:
        """Extract critical issues list."""
        lines = text.split("\n")
        issues = []

        in_section = False
        for line in lines:
            if "CRITICAL ISSUES" in line:
                in_section = True
                continue
            elif in_section and ("MAJOR CONCERNS" in line or "Strategic" in line):
                break
            elif in_section and line.strip().startswith("-"):
                issue = line.strip()[2:]
                issues.append(f"- {self._sanitize_for_markdown(issue)}")

        if not issues:
            issues = ["No critical issues identified"]

        return "\n".join(issues)

    def _extract_major_concerns(self, text: str) -> str:
        """Extract major concerns list."""
        lines = text.split("\n")
        concerns = []

        in_section = False
        for line in lines:
            if "MAJOR CONCERNS" in line:
                in_section = True
                continue
            elif in_section and ("Strategic" in line or line.startswith("#")):
                break
            elif in_section and line.strip().startswith("-"):
                concern = line.strip()[2:]
                concerns.append(f"- {self._sanitize_for_markdown(concern)}")

        return "\n".join(concerns) if concerns else "- No major concerns identified beyond critical issues"

    def _format_alternatives(self, alternatives: Dict) -> str:
        """Format strategic alternatives."""
        if not alternatives or "alternative_strategies" not in alternatives:
            return "See original business model analysis above."

        strategies = alternatives.get("alternative_strategies", "")
        return f"{strategies}"

    def generate_comparison(self, cases: List[Dict], comparison_title: Optional[str] = None) -> Dict:
        """
        Generate a comparison post between similar cases.

        Args:
            cases: List of case analyses to compare
            comparison_title: Custom title (auto-generated if None)

        Returns:
            Comparison post
        """
        if len(cases) < 2:
            logger.warning("Need at least 2 cases for comparison")
            return {}

        startup_names = [c.get("startup_name", "Unknown") for c in cases]

        if not comparison_title:
            comparison_title = f"Comparing {' vs '.join(startup_names[:2])}"
            if len(startup_names) > 2:
                comparison_title += f" (and {len(startup_names) - 2} others)"

        slug = slugify(comparison_title)

        # Extract key metrics for comparison
        comparison_data = []
        for case in cases:
            original_data = case.get("original_data", {})
            analysis = case.get("challenge_analysis", {})

            # Extract verdict
            verdict = "UNKNOWN"
            analysis_text = analysis.get("analysis", "")
            if "CONDITIONAL" in analysis_text:
                verdict = "CONDITIONAL"
            elif "PASS" in analysis_text:
                verdict = "PASS"
            elif "FAIL" in analysis_text:
                verdict = "FAIL"

            comparison_data.append({
                "name": case.get("startup_name", "Unknown"),
                "stage": original_data.get("stage", "Unknown"),
                "market": original_data.get("sectors", ["Unknown"])[0],
                "funding": original_data.get("total_funding", 0),
                "verdict": verdict,
            })

        # Generate comparison table
        table_rows = ["| Startup | Stage | Market | Funding | Verdict |", "| --- | --- | --- | --- | --- |"]
        for data in comparison_data:
            table_rows.append(
                f"| {data['name']} | {data['stage']} | {data['market']} | "
                f"${data['funding']:,} | {data['verdict']} |"
            )

        content = f"""# {comparison_title}

## Overview

This post compares the MIZHAR Challenge Mode analysis across {len(cases)} startups.

## Side-by-Side Comparison

{chr(10).join(table_rows)}

## Key Differences

"""
        for i, case in enumerate(cases):
            content += f"\n### {case.get('startup_name', 'Startup ' + str(i+1))}\n\n"
            original_data = case.get("original_data", {})
            content += f"- **Stage**: {original_data.get('stage', 'Unknown')}\n"
            content += f"- **Market**: {original_data.get('sectors', ['Unknown'])[0]}\n"
            content += f"- **Funding**: ${original_data.get('total_funding', 0):,}\n"
            content += f"- **Source**: {original_data.get('data_source', 'unknown')}\n"

        content += """\n## Verdict Distribution

"""
        verdict_counts = {}
        for data in comparison_data:
            verdict = data['verdict']
            verdict_counts[verdict] = verdict_counts.get(verdict, 0) + 1

        for verdict, count in verdict_counts.items():
            content += f"- **{verdict}**: {count}\n"

        front_matter = {
            "title": comparison_title,
            "slug": slug,
            "date": datetime.now().isoformat(),
            "author": "MIZHAR AI",
            "summary": f"Comparison of {len(cases)} startup analyses using MIZHAR Challenge Mode",
            "tags": ["comparison", "venture-analysis"],
        }

        post = {
            "slug": slug,
            "front_matter": front_matter,
            "content": content,
            "markdown": f"---\n{json.dumps(front_matter, indent=2)}\n---\n\n{content}",
            "comparison_data": comparison_data,
            "generated_at": datetime.now().isoformat(),
        }

        self.posts.append(post)
        return post

    def export_posts(self, directory: str) -> None:
        """
        Export all generated posts to markdown files.

        Args:
            directory: Directory to save posts
        """
        import os

        if not os.path.exists(directory):
            os.makedirs(directory)

        for post in self.posts:
            filename = os.path.join(directory, f"{post['slug']}.md")
            with open(filename, 'w') as f:
                f.write(post['markdown'])

            logger.info(f"Exported post: {filename}")

    def get_post_count(self) -> int:
        """Get total number of generated posts."""
        return len(self.posts)

    def generate_index(self) -> Dict:
        """
        Generate index of all posts.

        Returns:
            Index metadata
        """
        return {
            "total_posts": len(self.posts),
            "generated_at": datetime.now().isoformat(),
            "posts": [
                {
                    "slug": post['slug'],
                    "title": post['front_matter'].get('title'),
                    "date": post['front_matter'].get('date'),
                    "tags": post['front_matter'].get('tags', []),
                }
                for post in self.posts
            ]
        }

    def _estimate_read_time(self, content: str) -> int:
        """Estimate read time in minutes (assuming 200 words per minute)."""
        word_count = len(content.split())
        read_time = max(1, round(word_count / 200))
        return read_time

    def prepare_for_database(self, post: Dict, case_id: Optional[int] = None, case_name: Optional[str] = None) -> Dict:
        """
        Prepare a blog post for database insertion.

        Args:
            post: Generated blog post
            case_id: Associated case ID (optional)
            case_name: Associated case name (optional)

        Returns:
            Dictionary formatted for database
        """
        front_matter = post.get('front_matter', {})
        content = post.get('content', '')
        excerpt = front_matter.get('summary', content[:200])

        # Extract tags and sectors from front matter
        tags = front_matter.get('tags', [])
        sectors = []

        # Try to infer sectors from tags or case name
        if case_name:
            sectors = self._infer_sectors(case_name)

        db_post = {
            'title': front_matter.get('title', 'Untitled'),
            'slug': post.get('slug', ''),
            'excerpt': excerpt,
            'content': content,
            'case_id': case_id,
            'case_name': case_name,
            'tags': tags,
            'sectors': sectors,
            'published': False,  # Default to unpublished
            'author': front_matter.get('author', 'MIZHAR Analysis'),
            'read_time': self._estimate_read_time(content),
            'published_at': front_matter.get('date', datetime.now().isoformat()),
        }

        return db_post

    def _infer_sectors(self, case_name: str) -> List[str]:
        """Infer sectors based on case name and keywords."""
        sectors = []
        case_lower = case_name.lower()

        sector_keywords = {
            'AI': ['ai', 'artificial intelligence', 'machine learning', 'ml', 'gpt', 'claude'],
            'Software': ['software', 'saas', 'platform', 'app'],
            'Data Platform': ['data', 'databricks', 'lake', 'warehouse', 'analytics'],
            'Finance': ['fintech', 'finance', 'payment', 'banking'],
            'Healthcare': ['health', 'medical', 'biotech', 'pharma'],
        }

        for sector, keywords in sector_keywords.items():
            if any(keyword in case_lower for keyword in keywords):
                sectors.append(sector)

        # Default to Software if no match
        if not sectors:
            sectors = ['Software']

        return sectors

    def save_to_database(self, supabase_client: Any, post: Dict, case_id: Optional[int] = None, case_name: Optional[str] = None, publish: bool = False) -> Dict:
        """
        Save a blog post to Supabase database.

        Args:
            supabase_client: Initialized Supabase client
            post: Generated blog post
            case_id: Associated case ID (optional)
            case_name: Associated case name (optional)
            publish: Whether to publish immediately

        Returns:
            Database response
        """
        try:
            db_post = self.prepare_for_database(post, case_id, case_name)
            db_post['published'] = publish

            # Insert into database
            response = supabase_client.table('blog_posts').insert(db_post).execute()

            if response.data:
                logger.info(f"Saved blog post to database: {post.get('slug')}")
                return {'success': True, 'data': response.data, 'slug': post.get('slug')}
            else:
                logger.error(f"Failed to save blog post: {response}")
                return {'success': False, 'error': 'Failed to insert into database'}

        except Exception as e:
            logger.error(f"Database error saving blog post: {str(e)}")
            return {'success': False, 'error': str(e)}

    def save_all_to_database(self, supabase_client: Any, publish: bool = False) -> Dict:
        """
        Save all generated posts to database.

        Args:
            supabase_client: Initialized Supabase client
            publish: Whether to publish immediately

        Returns:
            Summary of save operations
        """
        results = {
            'total': len(self.posts),
            'saved': 0,
            'failed': 0,
            'posts': []
        }

        for post in self.posts:
            result = self.save_to_database(supabase_client, post, publish=publish)
            if result['success']:
                results['saved'] += 1
                results['posts'].append(result)
            else:
                results['failed'] += 1
                logger.error(f"Failed to save post: {post.get('slug')}")

        logger.info(f"Batch save complete: {results['saved']} saved, {results['failed']} failed")
        return results


def create_blog_generator() -> BlogGenerator:
    """Factory function to create configured blog generator."""
    return BlogGenerator()
