/**
 * Blog Detail Page
 * Path: /app/blog/[slug]
 *
 * Display full blog post content.
 */

'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';

interface BlogDetail {
  id: number;
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  case_id?: number;
  case_name?: string;
  tags: string[];
  sectors: string[];
  published_at: string;
  author: string;
  read_time: number;
}

interface PageProps {
  params: {
    slug: string;
  };
}

export default function BlogDetailPage({ params }: PageProps) {
  const [post, setPost] = useState<BlogDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadPost() {
      try {
        setLoading(true);
        const response = await fetch(`/api/blog/${params.slug}`);

        if (!response.ok) {
          throw new Error('Failed to load blog post');
        }

        const { data } = await response.json();
        setPost(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load blog post');
      } finally {
        setLoading(false);
      }
    }

    loadPost();
  }, [params.slug]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4" />
          <p className="text-gray-600">Loading blog post...</p>
        </div>
      </div>
    );
  }

  if (error || !post) {
    return (
      <div className="space-y-6">
        <Link href="/blog" className="text-blue-600 hover:text-blue-700 font-medium">
          ← Back to Blog
        </Link>
        <div className="bg-red-50 border border-red-200 rounded-lg p-8">
          <p className="text-red-800 mb-4">{error || 'Blog post not found'}</p>
          <Link href="/blog" className="text-red-600 hover:text-red-700 font-medium">
            Return to blog index
          </Link>
        </div>
      </div>
    );
  }

  const publishedDate = new Date(post.published_at);
  const formattedDate = publishedDate.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="space-y-8">
      {/* Back Link */}
      <Link href="/blog" className="text-blue-600 hover:text-blue-700 font-medium">
        ← Back to Blog
      </Link>

      {/* Header */}
      <div className="bg-white border border-gray-200 rounded-lg p-8">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          {post.title}
        </h1>

        {post.case_name && (
          <p className="text-lg text-gray-600 mb-6">
            Case Study: <span className="font-semibold">{post.case_name}</span>
          </p>
        )}

        {/* Metadata */}
        <div className="flex items-center gap-4 text-sm text-gray-600 pb-6 border-b border-gray-200">
          <span>{post.author}</span>
          <span>•</span>
          <span>{formattedDate}</span>
          <span>•</span>
          <span>{post.read_time} min read</span>
        </div>

        {/* Tags and Sectors */}
        <div className="mt-6 flex flex-wrap gap-3">
          {post.tags.map((tag) => (
            <span
              key={tag}
              className="inline-block px-3 py-1 text-sm font-medium bg-blue-100 text-blue-700 rounded-full"
            >
              {tag}
            </span>
          ))}
          {post.sectors.map((sector) => (
            <span
              key={sector}
              className="inline-block px-3 py-1 text-sm font-medium bg-gray-100 text-gray-700 rounded-full"
            >
              {sector}
            </span>
          ))}
        </div>
      </div>

      {/* Content */}
      <div className="bg-white border border-gray-200 rounded-lg p-8">
        <div className="prose prose-lg max-w-none text-gray-700 whitespace-pre-wrap">
          {post.content}
        </div>
      </div>

      {/* Related Case Study Link */}
      {post.case_id && post.case_name && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-8">
          <h2 className="text-2xl font-bold text-blue-900 mb-4">
            Read the Full Case Study
          </h2>
          <p className="text-blue-800 mb-6">
            Explore the complete Challenge Mode analysis for {post.case_name}.
          </p>
          <Link
            href={`/app/startup/cases/${post.case_id}`}
            className="inline-block px-6 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
          >
            View Case Details →
          </Link>
        </div>
      )}

      {/* Disclaimer */}
      <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-8">
        <p className="text-sm text-yellow-900">
          <strong>Disclaimer:</strong> This analysis is generated by AI based on public
          information and standard VC frameworks. It is not professional investment advice,
          a formal recommendation, or verified by direct company interaction. Use as
          research input only.
        </p>
      </div>

      {/* Navigation */}
      <div className="flex items-center justify-between pt-8 border-t border-gray-200">
        <Link
          href="/blog"
          className="text-blue-600 hover:text-blue-700 font-medium flex items-center gap-2"
        >
          ← Back to All Posts
        </Link>
        <Link
          href="/app/startup/cases"
          className="text-blue-600 hover:text-blue-700 font-medium flex items-center gap-2"
        >
          Explore Case Studies →
        </Link>
      </div>
    </div>
  );
}
