"use client"

import { useState } from "react"
import Topbar from "@/components/layout/topbar"
import { Send, Loader2 } from "lucide-react"

type Message = { id: number; role: "user" | "assistant"; text: string }

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([
    { id: 1, role: "assistant", text: "I'm Mizhar, your AI venture strategist. I have access to your venture profile and can answer questions about your business, market, competitors, and strategy. What would you like to explore?" }
  ])
  const [input, setInput] = useState("")
  const [loading, setLoading] = useState(false)

  const handleSend = async () => {
    if (!input.trim()) return
    const newMsg: Message = { id: messages.length + 1, role: "user", text: input }
    setMessages(prev => [...prev, newMsg])
    setInput("")
    setLoading(true)
    setTimeout(() => {
      setMessages(prev => [...prev, {
        id: prev.length + 1,
        role: "assistant",
        text: "I understand your question. Based on your venture profile, [response would be generated by Claude API]. In production, this would call the Anthropic API with your full context."
      }])
      setLoading(false)
    }, 1500)
  }

  return (
    <>
      <Topbar crumbs={[{ label: "Startup" }, { label: "AI Chat" }]} meta={[{ label: "Context: Full venture profile loaded" }]} />
      <div style={{ display: "flex", height: "calc(100vh - 120px)", flexDirection: "column" }}>
        <div style={{ flex: 1, overflow: "auto", padding: "24px 40px", display: "flex", flexDirection: "column", gap: 16 }}>
          {messages.map(msg => (
            <div key={msg.id} style={{ display: "flex", justifyContent: msg.role === "user" ? "flex-end" : "flex-start" }}>
              <div style={{
                maxWidth: "60%", padding: "12px 16px", borderRadius: 12,
                background: msg.role === "user" ? "var(--mz-orange)" : "var(--mz-cloud)",
                color: msg.role === "user" ? "white" : "var(--mz-ink)",
                fontSize: 14, lineHeight: 1.5
              }}>
                {msg.text}
              </div>
            </div>
          ))}
          {loading && (
            <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
              <Loader2 size={16} style={{ color: "var(--mz-orange)", animation: "spin 1s linear infinite" }} />
              <span style={{ fontSize: 13, color: "var(--mz-ink-3)" }}>Mizhar is thinking...</span>
            </div>
          )}
        </div>
        <div style={{ padding: "20px 40px", borderTop: "1px solid var(--mz-border-2)", display: "flex", gap: 10 }}>
          <input type="text" value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === "Enter" && handleSend()} placeholder="Ask Mizhar anything about your venture..." style={{ flex: 1, padding: "10px 14px", borderRadius: 10, border: "1px solid var(--mz-border)", fontSize: 14, outline: "none" }} />
          <button onClick={handleSend} disabled={!input.trim() || loading} className="btn btn--primary" style={{ gap: 6, opacity: !input.trim() || loading ? 0.4 : 1 }}>
            <Send size={14} />
          </button>
        </div>
      </div>
    </>
  )
}
